language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - "pip install -U setuptools pip"
  - "pip install pytest>=3.6 pytest-cov pytest-pep8 mock responses coveralls"
  - "pip install ."
script: "py.test"
after_success: "coveralls"
branches:
  only:
    - master
